sudo: false  # run on new infrastructure
language: python
python:
  - 3.6
# Cache Dependencies
cache: pip
addons:
  apt:
    packages:
    - optipng  # for optimize images plugin
    - libjpeg-progs  # for jpegtran for optimize images plugin

before_install:
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
# command to run tests
script:
  - invoke publish
after_success:

deploy:
  provider: pages
  local_dir: ..\blog.minchin.ca-master\
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
