# Global settings applied to the whole site.  
# 
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
[build]
  base    = ""
  publish = "output"
  command = "invoke build --publish --carefully"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  branch = "pelican"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "invoke build"

[build.environment]
  # list of supported version of Python
  # https://github.com/netlify/build-image/blob/focal/included_software.md
  PYTHON_VERSION = "3.8"
  # unused, but for faster builds
  RUBY_VERSION = "2.7.2"
